import {
  SiPython,
  SiTypescript,
  SiJavascript,
  SiCplusplus,
  SiSharp,
  SiGnubash,
  SiLinux,
  SiDocker,
  SiGithubactions,
  SiAmazon,
  SiGooglecloud,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiNodedotjs,
  SiVuedotjs,
  SiReact,
  SiFlask,
  SiDjango,
  SiGraphql,
  SiJest,
  SiJunit5,
  SiTensorflow,
  SiPandas,
  SiNextdotjs,
  SiTailwindcss,
  SiHtml5,
  SiFramer,
  SiVite,
  SiZod,
  SiGreensock,
  SiFigma,
  SiExpress,
  SiNestjs,
  SiVercel,
  SiTerraform,
  SiSupabase,
  SiLangchain,
  SiOpenai,
  SiAnthropic,
  SiGooglegemini,
  SiClaude,
} from "react-icons/si";

import {
  Network,
  Boxes,
  Waypoints,
  TestTube2,
  Bot,
  DatabaseZap,
  Database,
  Layers,
  Activity,
  Blocks,
  ScanSearch,
  Gauge,
  Workflow,
  Plug,
  MousePointerClick,
} from "lucide-react";
import { BrandIcon, GenericIcon, type Skill } from "./icons";

export const SKILLS: Skill[] = [
  {
    key: "python",
    label: "Python",
    tagline: "automation, data, backend glue.",
    icon: <BrandIcon Icon={SiPython} color="#3776AB" />,
  },
  {
    key: "typescript",
    label: "TypeScript",
    tagline: "safer JS for real apps.",
    icon: <BrandIcon Icon={SiTypescript} color="#3178C6" />,
  },
  {
    key: "javascript",
    label: "JavaScript",
    tagline: "the web’s default language.",
    icon: <BrandIcon Icon={SiJavascript} color="#F7DF1E" />,
  },
  {
    key: "cpp",
    label: "C++",
    tagline: "performance, systems, low-level work.",
    icon: <BrandIcon Icon={SiCplusplus} color="#00599C" />,
  },
  {
    key: "csharp",
    label: "C#",
    tagline: "services, apps, game dev.",
    icon: <BrandIcon Icon={SiSharp} color="#512BD4" />,
  },
  {
    key: "shell",
    label: "Shell",
    tagline: "fast scripting, faster debugging.",
    icon: <BrandIcon Icon={SiGnubash} color="#4EAA25" />,
  },

  {
    key: "linux",
    label: "Linux",
    tagline: "where servers actually live.",
    icon: <BrandIcon Icon={SiLinux} color="#FCC624" />,
  },
  {
    key: "docker",
    label: "Docker",
    tagline: "ship once, run anywhere.",
    icon: <BrandIcon Icon={SiDocker} color="#2496ED" />,
  },
  {
    key: "cicd",
    label: "CI/CD",
    tagline: "build, test, deploy, repeat.",
    icon: <BrandIcon Icon={SiGithubactions} color="#2088FF" />,
  },
  {
    key: "lb",
    label: "Load Balancing",
    tagline: "stable under real traffic.",
    icon: <GenericIcon icon={<Network size={40} className="text-ink-soft" />} />,
  },
  {
    key: "micro",
    label: "Microservices",
    tagline: "scale parts, not everything.",
    icon: <GenericIcon icon={<Boxes size={40} className="text-ink-soft" />} />,
  },

  {
    key: "aws",
    label: "AWS",
    tagline: "cloud for production workloads.",
    icon: <BrandIcon Icon={SiAmazon} color="#FF9900" />,
  },
  {
    key: "gcp",
    label: "Google Cloud",
    tagline: "cloud tools for apps + data.",
    icon: <BrandIcon Icon={SiGooglecloud} color="#4285F4" />,
  },

  {
    key: "postgres",
    label: "PostgreSQL",
    tagline: "structured data, done right.",
    icon: <BrandIcon Icon={SiPostgresql} color="#4169E1" />,
  },
  {
    key: "mysql",
    label: "MySQL",
    tagline: "classic SQL for web stacks.",
    icon: <BrandIcon Icon={SiMysql} color="#4479A1" />,
  },
  {
    key: "mongo",
    label: "MongoDB",
    tagline: "flexible docs, fast iteration.",
    icon: <BrandIcon Icon={SiMongodb} color="#47A248" />,
  },
  {
    key: "redis",
    label: "Redis",
    tagline: "cache and queues, super fast.",
    icon: <BrandIcon Icon={SiRedis} color="#DC382D" />,
  },

  {
    key: "node",
    label: "Node.js",
    tagline: "APIs, realtime, servers in JS.",
    icon: <BrandIcon Icon={SiNodedotjs} color="#339933" />,
  },
  {
    key: "vue",
    label: "Vue.js",
    tagline: "clean UI, quick shipping.",
    icon: <BrandIcon Icon={SiVuedotjs} color="#4FC08D" />,
  },
  {
    key: "react",
    label: "React",
    tagline: "dynamic, fast web apps.",
    icon: <BrandIcon Icon={SiReact} color="#61DAFB" />,
  },
  {
    key: "flask",
    label: "Flask",
    tagline: "small Python APIs, flexible.",
    icon: <BrandIcon Icon={SiFlask} color="#111111" />,
  },
  {
    key: "django",
    label: "Django",
    tagline: "batteries-included Python backend.",
    icon: <BrandIcon Icon={SiDjango} color="#092E20" />,
  },

  {
    key: "rest",
    label: "REST",
    tagline: "simple contracts, predictable APIs.",
    icon: <GenericIcon icon={<Waypoints size={40} className="text-ink-soft" />} />,
  },
  {
    key: "graphql",
    label: "GraphQL",
    tagline: "query exactly what the UI needs.",
    icon: <BrandIcon Icon={SiGraphql} color="#E10098" />,
  },
  {
    key: "pytest",
    label: "PyTest",
    tagline: "tests that keep you honest.",
    icon: <GenericIcon icon={<TestTube2 size={40} className="text-ink-soft" />} />,
  },
  {
    key: "jest",
    label: "Jest",
    tagline: "frontend tests without pain.",
    icon: <BrandIcon Icon={SiJest} color="#C21325" />,
  },
  {
    key: "junit",
    label: "JUnit",
    tagline: "solid testing for Java.",
    icon: <BrandIcon Icon={SiJunit5} color="#25A162" />,
  },
  {
    key: "tdd",
    label: "TDD",
    tagline: "write the test, then ship.",
    icon: <GenericIcon icon={<TestTube2 size={40} className="text-ink-soft" />} />,
  },

  {
    key: "llm",
    label: "LLMs",
    tagline: "chat, tools, and automation.",
    icon: <GenericIcon icon={<Bot size={40} className="text-ink-soft" />} />,
  },
  {
    key: "rag",
    label: "RAG",
    tagline: "answers grounded in real data.",
    icon: <GenericIcon icon={<DatabaseZap size={40} className="text-ink-soft" />} />,
  },
  {
    key: "tf",
    label: "TensorFlow",
    tagline: "ML training and inference pipelines.",
    icon: <BrandIcon Icon={SiTensorflow} color="#FF6F00" />,
  },
  {
    key: "pandas",
    label: "Pandas",
    tagline: "data wrangling and analysis.",
    icon: <BrandIcon Icon={SiPandas} color="#150458" />,
  },

  {
    key: "sql",
    label: "SQL",
    tagline: "the language every database speaks.",
    icon: <GenericIcon icon={<Database size={40} className="text-ink-soft" />} />,
  },

  {
    key: "reactnative",
    label: "React Native",
    tagline: "one codebase, both phones.",
    icon: <BrandIcon Icon={SiReact} color="#61DAFB" />,
  },
  {
    key: "next",
    label: "Next.js",
    tagline: "routing and rendering, batteries in.",
    icon: <BrandIcon Icon={SiNextdotjs} color="#000000" />,
  },
  {
    key: "tailwind",
    label: "Tailwind CSS",
    tagline: "design tokens, straight in the markup.",
    icon: <BrandIcon Icon={SiTailwindcss} color="#06B6D4" />,
  },
  {
    key: "htmlcss",
    label: "HTML/CSS",
    tagline: "the platform under every framework.",
    icon: <BrandIcon Icon={SiHtml5} color="#E34F26" />,
  },
  {
    key: "framer",
    label: "Framer Motion",
    tagline: "motion that explains, not decorates.",
    icon: <BrandIcon Icon={SiFramer} color="#0055FF" />,
  },
  {
    key: "vite",
    label: "Vite",
    tagline: "instant dev server, lean builds.",
    icon: <BrandIcon Icon={SiVite} color="#646CFF" />,
  },
  {
    key: "zustand",
    label: "Zustand",
    tagline: "small state, no ceremony.",
    icon: <GenericIcon icon={<Layers size={40} className="text-ink-soft" />} />,
  },
  {
    key: "zod",
    label: "Zod",
    tagline: "schemas that type themselves.",
    icon: <BrandIcon Icon={SiZod} color="#3E67B1" />,
  },
  {
    key: "gsap",
    label: "GSAP",
    tagline: "timeline animation with fine control.",
    icon: <BrandIcon Icon={SiGreensock} color="#0AE448" />,
  },
  {
    key: "figma",
    label: "Figma",
    tagline: "where the interface starts.",
    icon: <BrandIcon Icon={SiFigma} color="#F24E1E" />,
  },
  {
    key: "express",
    label: "Express",
    tagline: "unopinionated APIs, fast.",
    icon: <BrandIcon Icon={SiExpress} color="#000000" />,
  },
  {
    key: "nestjs",
    label: "NestJS",
    tagline: "structure for large Node services.",
    icon: <BrandIcon Icon={SiNestjs} color="#E0234E" />,
  },

  {
    key: "distributed",
    label: "Distributed Systems",
    tagline: "correct when the parts disagree.",
    icon: <GenericIcon icon={<Network size={40} className="text-ink-soft" />} />,
  },
  {
    key: "vercel",
    label: "Vercel",
    tagline: "push to deploy, preview per branch.",
    icon: <BrandIcon Icon={SiVercel} color="#000000" />,
  },
  {
    key: "terraform",
    label: "Terraform",
    tagline: "infrastructure you can review.",
    icon: <BrandIcon Icon={SiTerraform} color="#7B42BC" />,
  },
  {
    key: "observability",
    label: "Observability",
    tagline: "know it broke before users do.",
    icon: <GenericIcon icon={<Activity size={40} className="text-ink-soft" />} />,
  },
  {
    key: "supabase",
    label: "Supabase",
    tagline: "Postgres with the plumbing done.",
    icon: <BrandIcon Icon={SiSupabase} color="#3FCF8E" />,
  },
  {
    key: "pinecone",
    label: "Pinecone",
    tagline: "vector storage at query speed.",
    icon: <GenericIcon icon={<Blocks size={40} className="text-ink-soft" />} />,
  },

  {
    key: "vectorsearch",
    label: "Vector Search",
    tagline: "retrieval by meaning, not keywords.",
    icon: <GenericIcon icon={<ScanSearch size={40} className="text-ink-soft" />} />,
  },
  {
    key: "evals",
    label: "LLM Evals",
    tagline: "measure the model, don't trust it.",
    icon: <GenericIcon icon={<Gauge size={40} className="text-ink-soft" />} />,
  },
  {
    key: "agentic",
    label: "Agentic Orchestration",
    tagline: "many agents, one coherent run.",
    icon: <GenericIcon icon={<Workflow size={40} className="text-ink-soft" />} />,
  },
  {
    key: "mcp",
    label: "MCP",
    tagline: "one protocol for every tool.",
    icon: <GenericIcon icon={<Plug size={40} className="text-ink-soft" />} />,
  },
  {
    key: "langchain",
    label: "LangChain",
    tagline: "chains, tools, and memory.",
    icon: <BrandIcon Icon={SiLangchain} color="#1C3C3C" />,
  },
  {
    key: "openai",
    label: "OpenAI",
    tagline: "GPT models through the API.",
    icon: <BrandIcon Icon={SiOpenai} color="#412991" />,
  },
  {
    key: "anthropic",
    label: "Anthropic",
    tagline: "Claude models through the API.",
    icon: <BrandIcon Icon={SiAnthropic} color="#D97757" />,
  },
  {
    key: "gemini",
    label: "Gemini",
    tagline: "Google's models through the API.",
    icon: <BrandIcon Icon={SiGooglegemini} color="#8E75B2" />,
  },
  {
    key: "claudecode",
    label: "Claude Code",
    tagline: "agentic coding in the terminal.",
    icon: <BrandIcon Icon={SiClaude} color="#D97757" />,
  },
  {
    key: "cursor",
    label: "Cursor",
    tagline: "the editor with a model in it.",
    icon: (
      <GenericIcon icon={<MousePointerClick size={40} className="text-ink-soft" />} />
    ),
  },
];

/** Ordered display groups for the compact chips layout. */
export const SKILL_GROUPS: { label: string; keys: string[] }[] = [
  {
    label: "Languages",
    keys: ["python", "typescript", "javascript", "cpp", "csharp", "sql", "shell"],
  },
  {
    label: "Frameworks & APIs",
    keys: [
      "react",
      "reactnative",
      "next",
      "vue",
      "htmlcss",
      "tailwind",
      "framer",
      "gsap",
      "vite",
      "zustand",
      "zod",
      "figma",
      "node",
      "express",
      "nestjs",
      "flask",
      "django",
      "rest",
      "graphql",
    ],
  },
  {
    label: "Infra & Data",
    keys: [
      "linux",
      "docker",
      "cicd",
      "terraform",
      "aws",
      "gcp",
      "vercel",
      "observability",
      "postgres",
      "supabase",
      "mysql",
      "mongo",
      "redis",
      "pinecone",
      "lb",
      "micro",
      "distributed",
    ],
  },
  { label: "Testing & Quality", keys: ["pytest", "jest", "junit", "tdd"] },
  {
    label: "AI & ML",
    keys: [
      "llm",
      "rag",
      "vectorsearch",
      "evals",
      "agentic",
      "mcp",
      "langchain",
      "openai",
      "anthropic",
      "gemini",
      "claudecode",
      "cursor",
      "tf",
      "pandas",
    ],
  },
];
